server:
  port: 8080

spring:
  security:
    user:
      name: admin
      password: 123456
  datasource:
    url: jdbc:mysql://localhost:3306/security_demo?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

logging:
  level:
    web: info
    sql: debug


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.securitydemo.entity

